[2024-06-20T07:38:10.981+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:38:11.027+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:38:01.266138+00:00 [queued]>
[2024-06-20T07:38:11.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:38:01.266138+00:00 [queued]>
[2024-06-20T07:38:11.048+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T07:38:11.079+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): preprocess_test_data> on 2024-06-20 07:38:01.266138+00:00
[2024-06-20T07:38:11.089+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T07:38:11.092+0000] {standard_task_runner.py:63} INFO - Started process 103 to run task
[2024-06-20T07:38:11.092+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'preprocess_test_data', 'manual__2024-06-20T07:38:01.266138+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp003grb8o']
[2024-06-20T07:38:11.094+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask preprocess_test_data
[2024-06-20T07:38:11.188+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.preprocess_test_data manual__2024-06-20T07:38:01.266138+00:00 [running]> on host 223f65580fa9
[2024-06-20T07:38:11.397+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_test_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:38:01.266138+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:38:01.266138+00:00'
[2024-06-20T07:38:11.399+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:38:11.429+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:38:11.430+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 163, in preprocess_test_data
    data = process_data(data)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 34, in process_data
    numerical = process_numerical_df(numerical)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 52, in process_numerical_df
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-06-20T07:38:11.459+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=preprocess_test_data, run_id=manual__2024-06-20T07:38:01.266138+00:00, execution_date=20240620T073801, start_date=20240620T073811, end_date=20240620T073811
[2024-06-20T07:38:11.482+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task preprocess_test_data (No module named 'matplotlib'; 103)
[2024-06-20T07:38:11.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:38:11.563+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:38:11.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
