[2024-06-17T17:56:39.730+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:56:39.730+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:56:39.731+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:56:39.731+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:56:39.742+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:56:39.741+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:56:39.743+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:56:39.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.023 seconds
[2024-06-17T17:57:10.166+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:10.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:57:10.171+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:57:10.170+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:10.177+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:57:10.176+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:57:10.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:10.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.033 seconds
[2024-06-17T17:57:40.743+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:40.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:57:40.746+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:57:40.746+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:40.753+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:57:40.751+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:57:40.753+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:57:40.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.027 seconds
[2024-06-17T17:58:11.315+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:11.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:58:11.319+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:58:11.319+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:11.325+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:58:11.324+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:58:11.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:11.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.031 seconds
[2024-06-17T17:58:41.842+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:41.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:58:41.845+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:58:41.844+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:41.848+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:58:41.847+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:58:41.848+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:58:41.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.019 seconds
[2024-06-17T17:59:12.362+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:12.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:59:12.366+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:59:12.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:12.373+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:59:12.371+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:59:12.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:12.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.027 seconds
[2024-06-17T17:59:42.837+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:42.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T17:59:42.841+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:59:42.840+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:42.847+0000] {logging_mixin.py:151} INFO - [2024-06-17T17:59:42.846+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T17:59:42.847+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T17:59:42.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.026 seconds
[2024-06-17T18:00:13.394+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:13.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:00:13.398+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:00:13.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:13.404+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:00:13.403+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:00:13.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:13.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.029 seconds
[2024-06-17T18:00:43.891+0000] {processor.py:157} INFO - Started process (PID=479) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:43.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:00:43.895+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:00:43.895+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:43.900+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:00:43.899+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:00:43.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:00:43.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.028 seconds
[2024-06-17T18:01:14.464+0000] {processor.py:157} INFO - Started process (PID=534) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:14.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:01:14.468+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:01:14.468+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:14.474+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:01:14.473+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:01:14.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:14.488+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.028 seconds
[2024-06-17T18:01:45.000+0000] {processor.py:157} INFO - Started process (PID=589) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:45.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:01:45.005+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:01:45.004+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:45.010+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:01:45.009+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:01:45.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:01:45.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.030 seconds
[2024-06-17T18:02:15.590+0000] {processor.py:157} INFO - Started process (PID=644) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:15.591+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:02:15.594+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:02:15.593+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:15.600+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:02:15.598+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:02:15.600+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:15.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.029 seconds
[2024-06-17T18:02:46.154+0000] {processor.py:157} INFO - Started process (PID=699) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:46.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:02:46.159+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:02:46.159+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:46.166+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:02:46.165+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:02:46.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:02:46.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.035 seconds
[2024-06-17T18:03:16.663+0000] {processor.py:157} INFO - Started process (PID=754) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:16.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:03:16.667+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:03:16.666+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:16.675+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:03:16.673+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:03:16.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:16.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.034 seconds
[2024-06-17T18:03:47.128+0000] {processor.py:157} INFO - Started process (PID=809) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:47.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:03:47.132+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:03:47.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:47.137+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:03:47.136+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:03:47.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:03:47.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.025 seconds
[2024-06-17T18:04:17.629+0000] {processor.py:157} INFO - Started process (PID=864) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:17.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:04:17.631+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:04:17.631+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:17.634+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:04:17.634+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:04:17.635+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:17.647+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.020 seconds
[2024-06-17T18:04:43.220+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:43.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:04:43.222+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:04:43.222+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:43.227+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:04:43.226+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:04:43.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:04:43.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.020 seconds
[2024-06-17T18:05:14.017+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:14.019+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:05:14.022+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:05:14.022+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:14.032+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:05:14.031+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:05:14.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:14.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.039 seconds
[2024-06-17T18:05:44.559+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:44.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:05:44.563+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:05:44.562+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:44.568+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:05:44.567+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:05:44.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:05:44.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.027 seconds
[2024-06-17T18:06:15.224+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:15.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:06:15.228+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:06:15.228+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:15.234+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:06:15.233+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:06:15.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:15.247+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.027 seconds
[2024-06-17T18:06:45.856+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:45.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:06:45.862+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:06:45.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:45.868+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:06:45.867+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:06:45.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:06:45.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.031 seconds
[2024-06-17T18:07:16.258+0000] {processor.py:157} INFO - Started process (PID=313) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:16.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:07:16.262+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:07:16.262+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:16.269+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:07:16.268+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:07:16.269+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:16.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.031 seconds
[2024-06-17T18:07:46.695+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:46.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:07:46.703+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:07:46.703+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:46.716+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:07:46.714+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:07:46.719+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:07:46.843+0000] {logging_mixin.py:151} WARNING - --- Logging error ---
[2024-06-17T18:07:46.865+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-06-17T18:07:46.866+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
[2024-06-17T18:07:46.867+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/handlers.py", line 186, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
[2024-06-17T18:07:46.867+0000] {logging_mixin.py:151} WARNING - RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/dag_processor_manager/dag_processor_manager.log'>
[2024-06-17T18:07:46.868+0000] {logging_mixin.py:151} WARNING - Call stack:
[2024-06-17T18:07:46.873+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-06-17T18:07:46.874+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 60, in main
    args.func(args)
[2024-06-17T18:07:46.874+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2024-06-17T18:07:46.874+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2024-06-17T18:07:46.875+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 56, in wrapped_function
    return func(*args, **kwargs)
[2024-06-17T18:07:46.875+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 85, in scheduler
    _run_scheduler_job(job_runner, skip_serve_logs=args.skip_serve_logs)
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 843, in _execute
    self.processor_agent.start()
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 164, in start
    process.start()
[2024-06-17T18:07:46.876+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-06-17T18:07:46.877+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
[2024-06-17T18:07:46.877+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-06-17T18:07:46.877+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-06-17T18:07:46.877+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
[2024-06-17T18:07:46.877+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 259, in _run_processor_manager
    processor_manager.start()
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 494, in start
    return self._run_parsing_loop()
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 641, in _run_parsing_loop
    self.start_new_processes()
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 1099, in start_new_processes
    processor.start()
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 234, in start
    process.start()
[2024-06-17T18:07:46.878+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
[2024-06-17T18:07:46.879+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    DagFileProcessor.update_import_errors(
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 112, in wrapper
    return func(*args, **kwargs)
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
[2024-06-17T18:07:46.880+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 625, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
[2024-06-17T18:07:46.881+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
[2024-06-17T18:07:46.881+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
[2024-06-17T18:07:46.881+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
[2024-06-17T18:07:46.881+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
[2024-06-17T18:07:46.881+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
[2024-06-17T18:07:46.882+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
[2024-06-17T18:07:46.883+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
[2024-06-17T18:07:46.883+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
[2024-06-17T18:07:46.883+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
[2024-06-17T18:07:46.883+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
[2024-06-17T18:07:46.883+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
[2024-06-17T18:07:46.884+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
[2024-06-17T18:07:46.884+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
[2024-06-17T18:07:46.884+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
[2024-06-17T18:07:46.884+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 471, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", "\n".join(map(str, inspect.stack())))
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/inspect.py", line 1526, in stack
    return getouterframes(sys._getframe(1), context)
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/inspect.py", line 1503, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/inspect.py", line 1473, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/inspect.py", line 705, in getsourcefile
    if os.path.exists(filename):
[2024-06-17T18:07:46.885+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
[2024-06-17T18:07:46.886+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 470, in _exit_gracefully
    self.log.info("Exiting gracefully upon receiving signal %s", signum)
[2024-06-17T18:07:46.886+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
[2024-06-17T18:07:46.886+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
[2024-06-17T18:07:46.886+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
[2024-06-17T18:07:46.886+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/handlers.py", line 71, in emit
    logging.FileHandler.emit(self, record)
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1187, in emit
    StreamHandler.emit(self, record)
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
[2024-06-17T18:07:46.887+0000] {logging_mixin.py:151} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 470, in _exit_gracefully
    self.log.info("Exiting gracefully upon receiving signal %s", signum)
[2024-06-17T18:07:46.888+0000] {logging_mixin.py:151} WARNING - Message: 'Exiting gracefully upon receiving signal %s'
Arguments: (15,)
[2024-06-17T18:08:44.324+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:08:44.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:08:44.328+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:08:44.327+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:08:44.340+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:08:44.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:08:44.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:08:44.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.031 seconds
[2024-06-17T18:09:14.649+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:14.650+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:09:14.651+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:09:14.651+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:14.662+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:09:14.660+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:09:14.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:14.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.029 seconds
[2024-06-17T18:09:35.928+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:35.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:09:35.934+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:09:35.933+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:35.946+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:09:35.945+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 11, in <module>
    from airflow.operators.dagrun_operator import DagRunOrder
ImportError: cannot import name 'DagRunOrder' from 'airflow.operators.dagrun_operator' (unknown location)
[2024-06-17T18:09:35.947+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:09:35.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.039 seconds
[2024-06-17T18:10:02.270+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:02.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:10:02.276+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:10:02.275+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:02.832+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:10:02.831+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:10:02.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:02.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.575 seconds
[2024-06-17T18:10:54.746+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:54.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:10:54.748+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:10:54.748+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:55.364+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:10:55.363+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:10:55.364+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:10:55.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.627 seconds
[2024-06-17T18:11:25.459+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:25.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:11:25.460+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:11:25.460+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:25.645+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:11:25.644+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:11:25.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:25.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.194 seconds
[2024-06-17T18:11:55.792+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:55.794+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:11:55.797+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:11:55.797+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:56.026+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:11:56.026+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:11:56.027+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:11:56.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.247 seconds
[2024-06-17T18:12:26.286+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:26.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:12:26.293+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:12:26.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:26.506+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:12:26.505+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:12:26.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:26.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.231 seconds
[2024-06-17T18:12:56.838+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:56.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:12:56.840+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:12:56.840+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:56.971+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:12:56.970+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:12:56.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:12:56.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.144 seconds
[2024-06-17T18:21:14.879+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:14.880+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:21:14.881+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:21:14.881+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:15.514+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:21:15.513+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:21:15.514+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:15.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.647 seconds
[2024-06-17T18:21:45.588+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:45.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:21:45.589+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:21:45.589+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:45.811+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:21:45.810+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:21:45.812+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:21:45.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.233 seconds
[2024-06-17T18:22:19.271+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:19.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:22:19.273+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:22:19.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:19.871+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:22:19.870+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:22:19.871+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:19.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.610 seconds
[2024-06-17T18:22:49.900+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:49.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:22:49.901+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:22:49.901+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:50.104+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:22:50.104+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:22:50.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:22:50.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.214 seconds
[2024-06-17T18:23:20.256+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:20.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:23:20.259+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:23:20.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:20.476+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:23:20.475+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:23:20.476+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:20.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.232 seconds
[2024-06-17T18:23:50.712+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:50.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:23:50.716+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:23:50.716+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:50.937+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:23:50.936+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:23:50.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:23:50.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.236 seconds
[2024-06-17T18:25:37.415+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:25:37.417+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:25:37.424+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:25:37.423+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:25:37.756+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:25:37.754+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:25:37.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:25:37.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.353 seconds
[2024-06-17T18:26:08.059+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:26:08.060+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:26:08.064+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:26:08.064+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:26:08.273+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:26:08.272+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:26:08.274+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:26:08.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.228 seconds
[2024-06-17T18:27:02.031+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:27:02.032+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:27:02.033+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:27:02.033+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:27:02.632+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:27:02.631+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:27:02.633+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:27:02.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.611 seconds
[2024-06-17T18:32:28.696+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:28.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:32:28.698+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:32:28.698+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:29.330+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:32:29.329+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:32:29.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:29.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.645 seconds
[2024-06-17T18:32:59.465+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:59.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:32:59.467+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:32:59.467+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:59.671+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:32:59.670+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:32:59.671+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:32:59.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.216 seconds
[2024-06-17T18:33:29.781+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:33:29.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:33:29.784+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:33:29.784+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:33:30.016+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:33:30.015+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:33:30.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:33:30.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.248 seconds
[2024-06-17T18:34:00.306+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:34:00.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:34:00.314+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:34:00.313+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:34:00.544+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:34:00.543+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-06-17T18:34:00.544+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:34:00.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.252 seconds
[2024-06-17T18:54:41.743+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:54:41.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:54:41.745+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:54:41.745+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:54:42.809+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:54:42.808+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 52, in <module>
    prep_and_clean = PythonOperator(task_id="prepare data", python_callable=prep_data)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 804, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'prepare data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-06-17T18:54:42.810+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:54:42.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 1.078 seconds
[2024-06-17T18:55:13.099+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:13.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:55:13.107+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:13.107+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:13.780+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:13.779+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ml_pipeline.py", line 52, in <module>
    prep_and_clean = PythonOperator(task_id="prepare data", python_callable=prep_data)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 436, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 804, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'prepare data' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-06-17T18:55:13.780+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:13.787+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.692 seconds
[2024-06-17T18:55:28.375+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:28.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ml_pipeline.py for tasks to queue
[2024-06-17T18:55:28.472+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.472+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:28.828+0000] {processor.py:839} INFO - DAG(s) dict_keys(['ml_pipeline']) retrieved from /opt/airflow/dags/ml_pipeline.py
[2024-06-17T18:55:28.867+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.867+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:ml_pipeline
[2024-06-17T18:55:28.870+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.870+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:ml_pipeline
[2024-06-17T18:55:28.872+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.872+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:ml_pipeline
[2024-06-17T18:55:28.877+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.877+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2024-06-17T18:55:28.881+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.881+0000] {dag.py:2929} INFO - Creating ORM DAG for ml_pipeline
[2024-06-17T18:55:28.884+0000] {logging_mixin.py:151} INFO - [2024-06-17T18:55:28.884+0000] {dag.py:3677} INFO - Setting next_dagrun for ml_pipeline to 2024-07-17T00:00:00+00:00, run_after=2024-07-18T00:00:00+00:00
[2024-06-17T18:55:28.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ml_pipeline.py took 0.520 seconds
