[2024-06-20T06:06:17.134+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T06:06:17.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:06:15.358093+00:00 [queued]>
[2024-06-20T06:06:17.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:06:15.358093+00:00 [queued]>
[2024-06-20T06:06:17.163+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T06:06:17.179+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): prepare_data> on 2024-06-20 06:06:15.358093+00:00
[2024-06-20T06:06:17.185+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T06:06:17.187+0000] {standard_task_runner.py:63} INFO - Started process 287 to run task
[2024-06-20T06:06:17.189+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'prepare_data', 'manual__2024-06-20T06:06:15.358093+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp9fnqeo43']
[2024-06-20T06:06:17.191+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask prepare_data
[2024-06-20T06:06:17.248+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:06:15.358093+00:00 [running]> on host 56cacc86e873
[2024-06-20T06:06:17.323+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T06:06:15.358093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T06:06:15.358093+00:00'
[2024-06-20T06:06:17.325+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T06:06:17.327+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T06:06:17.328+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 21, in prepare_data
    from scripts import load_data
ImportError: cannot import name 'load_data' from 'scripts' (unknown location)
[2024-06-20T06:06:17.340+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=prepare_data, run_id=manual__2024-06-20T06:06:15.358093+00:00, execution_date=20240620T060615, start_date=20240620T060617, end_date=20240620T060617
[2024-06-20T06:06:17.352+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task prepare_data (cannot import name 'load_data' from 'scripts' (unknown location); 287)
[2024-06-20T06:06:17.363+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T06:06:17.378+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T06:06:17.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
