[2024-06-20T06:57:18.356+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T06:57:18.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:57:15.557362+00:00 [queued]>
[2024-06-20T06:57:18.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:57:15.557362+00:00 [queued]>
[2024-06-20T06:57:18.400+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T06:57:18.414+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): prepare_data> on 2024-06-20 06:57:15.557362+00:00
[2024-06-20T06:57:18.419+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T06:57:18.421+0000] {standard_task_runner.py:63} INFO - Started process 102 to run task
[2024-06-20T06:57:18.421+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'prepare_data', 'manual__2024-06-20T06:57:15.557362+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpgd6xhvvp']
[2024-06-20T06:57:18.422+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask prepare_data
[2024-06-20T06:57:18.458+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.prepare_data manual__2024-06-20T06:57:15.557362+00:00 [running]> on host 8abe912b0df1
[2024-06-20T06:57:18.531+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T06:57:15.557362+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T06:57:15.557362+00:00'
[2024-06-20T06:57:18.533+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T06:57:18.536+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T06:57:18.536+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 21, in prepare_data
    from scripts import load_data
ImportError: cannot import name 'load_data' from 'scripts' (unknown location)
[2024-06-20T06:57:18.548+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=prepare_data, run_id=manual__2024-06-20T06:57:15.557362+00:00, execution_date=20240620T065715, start_date=20240620T065718, end_date=20240620T065718
[2024-06-20T06:57:18.560+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task prepare_data (cannot import name 'load_data' from 'scripts' (unknown location); 102)
[2024-06-20T06:57:18.596+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T06:57:18.623+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T06:57:18.626+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
