[2024-06-20T08:45:53.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T08:45:53.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.train_and_test_model manual__2024-06-20T08:40:17.774745+00:00 [queued]>
[2024-06-20T08:45:53.478+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.train_and_test_model manual__2024-06-20T08:40:17.774745+00:00 [queued]>
[2024-06-20T08:45:53.480+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T08:45:53.535+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_test_model> on 2024-06-20 08:40:17.774745+00:00
[2024-06-20T08:45:53.554+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T08:45:53.560+0000] {standard_task_runner.py:63} INFO - Started process 1175 to run task
[2024-06-20T08:45:53.559+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_and_test_model', 'manual__2024-06-20T08:40:17.774745+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpwli93t6q']
[2024-06-20T08:45:53.563+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask train_and_test_model
[2024-06-20T08:45:53.707+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.train_and_test_model manual__2024-06-20T08:40:17.774745+00:00 [running]> on host 12086e25b8f3
[2024-06-20T08:45:54.095+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RCH4CKERS' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='train_and_test_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T08:40:17.774745+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T08:40:17.774745+00:00'
[2024-06-20T08:45:54.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T08:45:59.512+0000] {logging_mixin.py:188} INFO - Logistic Regression
[2024-06-20T08:45:59.536+0000] {logging_mixin.py:188} INFO - 2641
[2024-06-20T08:45:59.574+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T08:45:59.576+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 176, in train_and_test_model
    model = train_model(train_data)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 77, in train_model
    model = fit_model(model, x, y)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 101, in fit_model
    model.fit(X, y)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py", line 1223, in fit
    X, y = self._validate_data(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1289, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric, estimator=estimator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 1311, in _check_y
    _assert_all_finite(y, input_name="y", estimator_name=estimator_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 111, in _assert_all_finite
    raise ValueError("Input contains NaN")
ValueError: Input contains NaN
[2024-06-20T08:45:59.623+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=train_and_test_model, run_id=manual__2024-06-20T08:40:17.774745+00:00, execution_date=20240620T084017, start_date=20240620T084553, end_date=20240620T084559
[2024-06-20T08:45:59.667+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task train_and_test_model (Input contains NaN; 1175)
[2024-06-20T08:45:59.710+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T08:45:59.760+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T08:45:59.766+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
